### ISSUE TITLE
[FEATURE]:May it be possible to build Homer3 on python?

### ISSUE THREAD

**Issue by RyanY11** [BUNPC/Homer3#126]
Hi, just a little question here, why choose MATLAB?
If it can build on Python environment, what is the main obstruct？
Thanks!

**Comment by sstucker** [comment]
Homer and its predecessors are based firmly in MATLAB. There is no reason for this other than it was the tool of choice for the project when it began over 10 years ago.

It is quite possible to port Homer user functions to Python, depending on packages like scipy. In fact, the next generation of large scale fNIRS apps are taking shape in Python to take advantage of its portability. Homer will remain a MATLAB toolbox.
