### ISSUE TITLE
homer3_install_win.zip is missing from Install folder

### ISSUE THREAD

**Issue by rderollepot** [BUNPC/Homer3#14]
Hello,

Currently, the installation instructions if you do not have Matlab state that you need to go to the homer3 _Install_ folder and unzip _homer3_install_win.zip_. Problem: it is not there.

In my lab, we use both the source and compiled versions of Homer, so here is what I did to get the installation files:

1. In Matlab, navigate to homer3 root folder
2. run `setpaths`
3. run `createInstallFile`

Doing that, I obtained the archive _homer3_install_win.zip_ in the _Install_ folder, that I could then use to follow the installation instructions for the case when you do not have Matlab.

It would be helpful to either document the process to build the installation files (as I am not sure what I did is correct), or to supply the archive (via releases maybe ?).

**Comment by sstucker** [comment]
We now supply releases via GitHub, but should you want to build your own from source there should be instructions available via a README @jayd1860 is this up to date?

**Comment by rderollepot** [comment]
This is great that you now provide releases, I think it resolves this issue 👍

**Comment by sstucker** [comment]
We are going to try to make them more frequent as well. Thanks!
