### ISSUE TITLE
GLM T score

### ISSUE THREAD

**Issue by yakirme** [BUNPC/Homer3#18]
We want to calculate the t-score from the beta values.
See for example - https://www.brainvoyager.com/bv/doc/UsersGuide/StatisticalAnalysis/TheGeneralLinearModel.html

For that we need to extract the regressors for the GLM fit. Where can we find them?

Thank you

**Comment by sstucker** [comment]
Has this been implemented since @mayucel ?

**Comment by mayucel** [comment]
This has been implemented. You can find the t and p values for the GLM regressors under ProcResultClass.misc.hmrstats under Homer3 output files.

**Comment by mayucel** [comment]
Please see here for further info:
[https://github.com/BUNPC/Homer3/wiki/Input-and-Output-Names-and-Formats](url)
