### ISSUE TITLE
[BUG]: SNIRF file cannot be loaded - `data` field is invalid

### ISSUE THREAD

**Issue by JakubOrlinski97** [BUNPC/Homer3#188]
### Version of Homer3 you are using
Homer3 v1.80.2; main release

### Your environment (MATLAB environment and OS)
MATLAB Runtime R2017b (9.3); Windows 10 64-bit

### Description of the issue
When loading a standalone SNIRF file, the command line reports there is an issue with the `data` field. Compliance with the SNIRF data format was ensured, but the error still exists.

The only difference from any normal SNIRF file is that the dataTimeSeries is not proper fNIRS data, but a string of random doubles used for testing the output of an export program.

All the data formats were checked and extra optional fields were included in the file. Also, the pysnirf2 library was used to check the validity of the file and adherence to the specification, and the file has no errors.

_Interestingly, the test.snirf file provided in the repository gets loaded correctly, even though pysnirf2 reports multiple FATAL errors._

**Steps to reproduce:**
[snirf_test.zip](https://github.com/BUNPC/Homer3/files/13440188/snirf_test.zip)

Find the attached file (snirf_test.snirf) and include it in your SubjDataSample folder. Then try to open Homer3 and notice the output in the CLI - it reports an error about the `data` field.

**Expected behavior:**
The file should load correctly and without issue.

**Actual behavior:**

The file does not get loaded, no matter the configuration, included fields and so on.

The error that is visible in the output is not very informative:
DataFilesClass.ErrorCheck - ERROR: In file "snirf_test.snirf" "data"  field is invalid.. File will not be added to data set

pysnirf2 output for my file's validity:
//formatVersion                                       WARNING FIXED_LENGTH_STRING         
/nirs/metaDataTags/SubjectID                          WARNING FIXED_LENGTH_STRING         
/nirs/metaDataTags/MeasurementDate                    WARNING FIXED_LENGTH_STRING         
/nirs/metaDataTags/MeasurementTime                    WARNING FIXED_LENGTH_STRING         
/nirs/metaDataTags/LengthUnit                         WARNING FIXED_LENGTH_STRING         
/nirs/metaDataTags/TimeUnit                           WARNING FIXED_LENGTH_STRING         
/nirs/metaDataTags/FrequencyUnit                      WARNING FIXED_LENGTH_STRING         

Found 40 OK      (hidden)
Found 40 INFO    (hidden)
Found 7 WARNING
Found 0 FATAL  

and the validity output for the test.snirf file included in the project:
/nirs/data1/measurementList1/sourceIndex              FATAL   INVALID_DATASET_TYPE    
/nirs/data1/measurementList1/detectorIndex            FATAL   INVALID_DATASET_TYPE    
/nirs/data1/measurementList1/wavelengthIndex          FATAL   INVALID_DATASET_TYPE    
/nirs/data1/measurementList1/dataType                 FATAL   INVALID_DATASET_TYPE    
/nirs/data1/measurementList1/dataTypeIndex            FATAL   INVALID_DATASET_TYPE    
/nirs/data1/measurementList1/moduleIndex              FATAL   INVALID_DATASET_TYPE    
/nirs/data1/measurementList2/sourceIndex              FATAL   INVALID_DATASET_TYPE    
/nirs/data1/measurementList2/detectorIndex            FATAL   INVALID_DATASET_TYPE    
/nirs/data1/measurementList2/wavelengthIndex          FATAL   INVALID_DATASET_TYPE    
/nirs/data1/measurementList2/dataType                 FATAL   INVALID_DATASET_TYPE    
/nirs/data1/measurementList2/dataTypeIndex            FATAL   INVALID_DATASET_TYPE    
/nirs/data1/measurementList2/moduleIndex              FATAL   INVALID_DATASET_TYPE    
/nirs/data1/measurementList3/sourceIndex              FATAL   INVALID_DATASET_TYPE    
/nirs/data1/measurementList3/detectorIndex            FATAL   INVALID_DATASET_TYPE    
/nirs/data1/measurementList3/wavelengthIndex          FATAL   INVALID_DATASET_TYPE    
/nirs/data1/measurementList3/dataType                 FATAL   INVALID_DATASET_TYPE    
/nirs/data1/measurementList3/dataTypeIndex            FATAL   INVALID_DATASET_TYPE    
/nirs/data1/measurementList3/moduleIndex              FATAL   INVALID_DATASET_TYPE    
/nirs/data1/measurementList4/sourceIndex              FATAL   INVALID_DATASET_TYPE    
/nirs/data1/measurementList4/detectorIndex            FATAL   INVALID_DATASET_TYPE    
/nirs/data1/measurementList4/wavelengthIndex          FATAL   INVALID_DATASET_TYPE    
/nirs/data1/measurementList4/dataType                 FATAL   INVALID_DATASET_TYPE    
/nirs/data1/measurementList4/dataTypeIndex            FATAL   INVALID_DATASET_TYPE    
/nirs/data1/measurementList4/moduleIndex              FATAL   INVALID_DATASET_TYPE    
/nirs/stim1/data                                      FATAL   INVALID_DATASET_SHAPE   
/nirs/aux1/dataTimeSeries                             FATAL   INVALID_DATASET_SHAPE   
/nirs/aux2/dataTimeSeries                             FATAL   INVALID_DATASET_SHAPE   
/nirs/aux3/dataTimeSeries                             FATAL   INVALID_DATASET_SHAPE   
/nirs/aux4/dataTimeSeries                             FATAL   INVALID_DATASET_SHAPE   
/nirs/aux5/dataTimeSeries                             FATAL   INVALID_DATASET_SHAPE   
/nirs/aux6/dataTimeSeries                             FATAL   INVALID_DATASET_SHAPE   
/nirs/aux7/dataTimeSeries                             FATAL   INVALID_DATASET_SHAPE   
/nirs/aux8/dataTimeSeries                             FATAL   INVALID_DATASET_SHAPE   

Found 53 OK      (hidden)
Found 42 INFO    (hidden)
Found 0 WARNING
Found 33 FATAL

**Comment by JakubOrlinski97** [comment]
In the end this was an issue of the export algorithm, not of Homer. Better documentation could have helped but it is now resolved.

**Comment by sslyutov** [comment]
I have the same issue 
really hard to get any details about the cause
What was the workaround/solution?
