### ISSUE TITLE
Inputting new functions into Homer 3

### ISSUE THREAD

**Issue by danspw** [BUNPC/Homer3#26]
Hello,

I'm trying to find a way to input a new function into Homer 3. Specifically, I'd like to input the autoregressive prewhitening algorithm (AR-IRLS) from NIRS Toolbox into Homer 3. The issue is that this algorithm is considered a class instead of a function, so I'm not sure how to input it properly for Homer 3. Are there any tutorials on this or has someone else experienced a similar issue?

Thanks,

P

**Comment by sstucker** [comment]
This page offers information on how to do this along with the need-to-know workings of Homer3. Re-open an issue or post at https://openfnirs.org/community/homer3-forum/.
