### ISSUE TITLE
Dealing with Biopac .oxy data

### ISSUE THREAD

**Issue by iPsych** [BUNPC/Homer3#5]
Hello,

In my knowledge, Homer is the only open-source fNIRS analysis platform support the data recorded with COBI studio. 

Currently, I use the (barely working) in-house script based on below.
http://www.physiologicalcomputing.net/?page_id=2621
Is there any update/support in Homer3 for COBI .oxy data?

**Comment by sstucker** [comment]
We are working with to make sure most software can export SNIRF files, the standard hdf5 data format that Homer3 loads. In the meantime, you can create your own SNIRF hdf5 files according to [the specification,](https://github.com/fNIRS/snirf/blob/master/snirf_specification.md) or generate a nirs style structure.
