### ISSUE TITLE
Error when running Wavelet motion correction 

### ISSUE THREAD

**Issue by Mavelasq** [BUNPC/Homer3#64]
When I try to run the Wavelet motion correction function through the stream edit GUI I get an error saying that intensity_to_delta_OD function is needed first even when that function is already in the stream before the wavelet function. When I click continue anyway Homer gives me an error saying that the filter exceeds the Nyquist frequency.

**Comment by sstucker** [comment]
Please direct issues of this nature to the forum https://openfnirs.org/community/homer3-forum/
